# 🛡️ Cyber Attack Type Classification - Multiclass Logistic Regression

**🇹🇷 Türkçe:**
Bu projede, siber saldırı verilerini (`7-cyber_attack_data.csv`) inceleyerek ağ trafiği özelliklerine dayalı siber saldırı türlerini (`attack_type`) sınıflandırıyoruz[cite: 7]. İkiden fazla sınıfımız olduğu için Çok Sınıflı Sınıflandırma (Multiclass Classification) stratejilerini uygulayacağız[cite: 7].

**🇬🇧 English:**
In this project, we analyze cyber attack data (`7-cyber_attack_data.csv`) to classify cyber attack types (`attack_type`) based on network traffic features[cite: 7]. Since we have more than two classes, we will apply Multiclass Classification strategies[cite: 7].

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../../Data/7-cyber_attack_data.csv")

In [3]:
df.columns

Index(['src_packet_rate', 'dst_packet_rate', 'avg_payload_size',
       'connection_duration', 'tcp_flag_count', 'avg_interarrival_time',
       'failed_login_attempts', 'unusual_port_activity_score',
       'session_entropy', 'avg_response_delay', 'attack_type'],
      dtype='str')

In [4]:
df.head()

,src_packet_rate,dst_packet_rate,avg_payload_size,connection_duration,tcp_flag_count,avg_interarrival_time,failed_login_attempts,unusual_port_activity_score,session_entropy,avg_response_delay,attack_type
0,-1.286132,-0.648334,1.044115,-0.469715,0.789859,-0.083727,-1.647309,-1.316412,1.011910,-0.898063,2
1,-0.222224,2.083232,1.191114,-1.354527,-0.956992,1.696028,-1.070406,0.981403,-1.628798,1.377594,0
2,-0.431963,0.375745,-1.370334,0.819214,0.345243,1.389447,-1.904130,1.292602,0.925545,0.232705,0
3,-0.912633,0.986988,-0.690042,2.014628,-0.442260,0.590347,-1.819353,1.560938,0.823755,0.517762,0
4,-0.367056,1.667892,0.879172,2.214276,1.846338,-0.894047,1.543838,0.931103,-1.015210,1.061845,1


## ⚙️ Veri Ayırma İşlemi / Data Splitting

**🇹🇷 Türkçe:**
Hedef değişkenimiz olan `attack_type` (saldırı türü) sütununu özelliklerden (features) ayırıyoruz[cite: 7]. Ardından modelin performansını daha sonra ölçebilmek için verimizi Eğitim (Train) ve Test setlerine bölüyoruz[cite: 7].

**🇬🇧 English:**
We separate our target variable `attack_type` from the features[cite: 7]. Then, we split our data into Training and Test sets to evaluate the model's performance later[cite: 7].

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop("attack_type",axis=1)
y = df["attack_type"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 15)

## 🤖 Standart Lojistik Regresyon / Default Logistic Regression

**🇹🇷 Türkçe:**
Standart bir Lojistik Regresyon (Logistic Regression) modeli oluşturup eğitim verilerimiz üzerinde eğitiyoruz[cite: 7]. Sonrasında Doğruluk (Accuracy) ve Karmaşıklık Matrisi (Confusion Matrix) metrikleriyle model performansımızı analiz ediyoruz[cite: 7].

**🇬🇧 English:**
We instantiate a standard Logistic Regression model and train it on our training data[cite: 7]. Afterwards, we analyze our model performance using Accuracy and Confusion Matrix metrics[cite: 7].

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
logistic = LogisticRegression()

In [10]:
logistic.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [11]:
y_pred = logistic.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [13]:
accuracy = accuracy_score(y_pred, y_test)
cm = confusion_matrix(y_pred, y_test)

In [14]:
print(accuracy)
print(cm)

0.7866666666666666
[[82  2  6]
 [17 72 10]
 [ 6 23 82]]


## 🔄 Çok Sınıflı Sınıflandırma Stratejileri / Multiclass Classification Strategies

**🇹🇷 Türkçe:**
Lojistik Regresyon ikili (binary) bir sınıflandırıcı olduğu için, üç farklı saldırı türünü sınıflandırırken `OneVsOneClassifier` (Bire Karşı Bir) ve `OneVsRestClassifier` (Bire Karşı Hepsi) stratejilerini deniyoruz[cite: 7]. Bu yöntemler, modelin doğruluğunu optimize etmemize yardımcı olur[cite: 7].

**🇬🇧 English:**
Since Logistic Regression is a binary classifier, we experiment with `OneVsOneClassifier` and `OneVsRestClassifier` strategies to classify the three different attack types[cite: 7]. These methods help us optimize the accuracy of the model[cite: 7].

In [15]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier

In [16]:
onevsone = OneVsOneClassifier(LogisticRegression())
onevsrest =OneVsRestClassifier(LogisticRegression())

In [17]:
onevsrest.fit(X_train, y_train)
y_pred = onevsrest.predict(X_test)
accuracy = accuracy_score(y_pred, y_test)
cm = confusion_matrix(y_pred, y_test)
print(cm)
print(accuracy)

[[83  2  6]
 [16 69  9]
 [ 6 26 83]]
0.7833333333333333


In [18]:
onevsone.fit(X_train, y_train)
y_pred = onevsone.predict(X_test)
accuracy = accuracy_score(y_pred, y_test)
cm = confusion_matrix(y_pred, y_test)
print(cm)
print(accuracy)

[[84  3  4]
 [12 72 11]
 [ 9 22 83]]
0.7966666666666666
