In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [79]:
df = pd.read_csv("../../Data/insurance.csv")

In [80]:
df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [81]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X = df[["age","sex","bmi","children","smoker","region"]]
y = df["charges"]

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

In [85]:
X_train

,age,sex,bmi,children,smoker,region
1256,51,female,36.385,3,no,northwest
147,51,female,37.730,1,no,southeast
1042,20,male,30.685,0,yes,northeast
889,57,male,33.630,1,no,northwest
650,49,female,42.680,2,no,southeast
...,...,...,...,...,...,...
1223,20,female,24.420,0,yes,southeast
667,40,female,32.775,2,yes,northwest
156,48,male,24.420,0,yes,southeast
384,44,male,22.135,2,no,northeast


In [86]:
X_test

,age,sex,bmi,children,smoker,region
38,35,male,36.67,1,yes,northeast
126,19,female,28.30,0,yes,southwest
479,23,male,32.56,0,no,southeast
10,25,male,26.22,0,no,northeast
195,19,male,30.59,0,no,northwest
...,...,...,...,...,...,...
1059,32,male,33.82,1,no,northwest
303,28,female,33.00,2,no,southeast
335,64,male,34.50,0,no,southwest
792,22,female,23.18,0,no,northeast


data leakage önlemek için encodingleri şimdi yapıcaz

In [87]:
X_train["sex"] = X_train["sex"].map({"male":0, "female":1})
X_test["sex"] = X_test["sex"].map({"male":0, "female":1})

In [88]:
X_train

,age,sex,bmi,children,smoker,region
1256,51,1,36.385,3,no,northwest
147,51,1,37.730,1,no,southeast
1042,20,0,30.685,0,yes,northeast
889,57,0,33.630,1,no,northwest
650,49,1,42.680,2,no,southeast
...,...,...,...,...,...,...
1223,20,1,24.420,0,yes,southeast
667,40,1,32.775,2,yes,northwest
156,48,0,24.420,0,yes,southeast
384,44,0,22.135,2,no,northeast


In [89]:
X_train["smoker"] = X_train["smoker"].map({"yes":1, "no":0})
X_test["smoker"] = X_test["smoker"].map({"yes":1, "no":0})

In [90]:
X_train["region"].unique()

<StringArray>
['northwest', 'southeast', 'northeast', 'southwest']
Length: 4, dtype: str

In [91]:
X_train = pd.get_dummies(X_train, columns=["region"], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=["region"], drop_first=True, dtype=int)

In [92]:
X_train

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
1256,51,1,36.385,3,0,1,0,0
147,51,1,37.730,1,0,0,1,0
1042,20,0,30.685,0,1,0,0,0
889,57,0,33.630,1,0,1,0,0
650,49,1,42.680,2,0,0,1,0
...,...,...,...,...,...,...,...,...
1223,20,1,24.420,0,1,0,1,0
667,40,1,32.775,2,1,1,0,0
156,48,0,24.420,0,1,0,1,0
384,44,0,22.135,2,0,0,0,0


In [93]:
from sklearn.preprocessing import StandardScaler

In [94]:
scaler = StandardScaler()

In [95]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [96]:
X_train

array([[ 0.8143715 ,  1.00938988,  0.92361714, ...,  1.78316783,
        -0.60254238, -0.57375304],
       [ 0.8143715 ,  1.00938988,  1.14285117, ..., -0.56079971,
         1.65963429, -0.57375304],
       [-1.38518087, -0.99069747, -0.00547876, ..., -0.56079971,
        -0.60254238, -0.57375304],
       ...,
       [ 0.60151159, -0.99069747, -1.02666924, ..., -0.56079971,
         1.65963429, -0.57375304],
       [ 0.31769838, -0.99069747, -1.3991226 , ..., -0.56079971,
        -0.60254238, -0.57375304],
       [ 0.60151159, -0.99069747,  0.01000618, ..., -0.56079971,
        -0.60254238, -0.57375304]], shape=(1070, 8))

In [97]:
X_test

array([[-0.32088134, -0.99069747,  0.97007193, ..., -0.56079971,
        -0.60254238, -0.57375304],
       [-1.45613417,  1.00938988, -0.39423204, ..., -0.56079971,
        -0.60254238,  1.74291017],
       [-1.17232096, -0.99069747,  0.30014489, ..., -0.56079971,
         1.65963429, -0.57375304],
       ...,
       [ 1.73676442, -0.99069747,  0.6163635 , ..., -0.56079971,
        -0.60254238,  1.74291017],
       [-1.24327426,  1.00938988, -1.22878835, ..., -0.56079971,
        -0.60254238, -0.57375304],
       [ 0.8853248 ,  1.00938988,  0.42076436, ..., -0.56079971,
        -0.60254238,  1.74291017]], shape=(268, 8))

In [98]:
from sklearn.linear_model import LinearRegression

In [99]:
regression = LinearRegression()

In [100]:
regression.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](8,)","[3692.06, -21.27,2082.9 ,...,-168.34,-474.64,-420.51]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,1.353e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(8)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](8,)","[40.53,37.78,34.6 ,...,31.05,28.89,18.45]"


In [101]:
y_pred = regression.predict(X_test)

In [102]:
y_pred

array([33890.21746398, 25233.16770791,  3791.35859501,  3236.48950223,
        2753.78589644,  8033.19434312,   986.8359004 , 34996.35894003,
        8442.93273586,  8820.10937347,  3895.51369222,  6211.06335152,
       35977.64400112, 32768.35404822,  5519.16539467, 37357.53637207,
       27197.40132169,  9381.17555737, 30153.99797749,  8237.76932057,
        5443.36483562,  9757.7881789 ,  3380.6687726 , 18562.02604072,
       11847.3988793 ,  8691.27557737,  7683.21386456, 39069.50138105,
        3714.68510187,   -48.3377788 ,  6882.26406994,  9270.97591921,
        5484.24601192, 41119.11931005,  6971.11105692,  5577.71534461,
        5458.22851457,  3827.22533323,  6328.95680314, 11561.51731191,
        7167.25740263, 10780.62087794, 15750.70435474,  2725.46683683,
       11149.61900748, 11239.45478649, 11669.62825239,  6451.20447244,
        9674.10638387, 28654.83352765,  1286.48507399,  2157.91909444,
        9004.72207652, 10266.46054073, 12935.60069719, 26766.68773927,
      

In [103]:
from sklearn.metrics import r2_score

In [104]:
r2_score(y_test, y_pred)

0.7709928565663493